import { buildConsultazioneRowViewModel } from './buildConsultazioneRowViewModel.js'

export function buildConsultazioneDemoRows() {
  const demoRows = [
    {
      id: 'demo-1',
      riga_numero: 1,
      conto_id: '4-00-25-0010',
      conto_codice: '4 00 25 0010',
      conto_descrizione: 'Materie prime c/acquisti',
      descrizione_riga: 'Fattura n. 25/0001 - Fornitore Alfa Srl',
      importo_dare: 5080.12,
      importo_avere: 0,
      controparte: 'Fornitore Alfa Srl',
      prima_nota: {
        id: 'pn-demo-1',
        numero_registrazione: '000001',
        data_registrazione: '2026-01-02',
        data_documento: '2026-01-02',
        numero_documento: 'FAC 25/0001',
        causale_codice: 'FF',
        causale_iva_codice: '22',
        cliente_fornitore_nome: 'Fornitore Alfa Srl',
        registro_iva_codice: '25/0001',
        protocollo_iva: '5.080,12',
        totale_dare: 6197.75,
        totale_avere: 6197.75,
      },
    },
    {
      id: 'demo-2',
      riga_numero: 2,
      conto_id: '1-00-10-001',
      conto_codice: '1 00 10 001',
      conto_descrizione: 'IVA a credito',
      descrizione_riga: 'IVA 22% fattura n. 25/0001',
      importo_dare: 1117.63,
      importo_avere: 0,
      controparte: 'Fornitore Alfa Srl',
      prima_nota: {
        id: 'pn-demo-1',
        numero_registrazione: '000001',
        data_registrazione: '2026-01-02',
        data_documento: '2026-01-02',
        numero_documento: 'FAC 25/0001',
        causale_codice: 'FF',
        causale_iva_codice: '22',
        cliente_fornitore_nome: 'Fornitore Alfa Srl',
        registro_iva_codice: '25/0001',
        protocollo_iva: '5.080,12',
        totale_dare: 6197.75,
        totale_avere: 6197.75,
      },
    },
    {
      id: 'demo-3',
      riga_numero: 3,
      conto_id: '2-01-10-001',
      conto_codice: '2 01 10 001',
      conto_descrizione: 'Debiti v/fornitori',
      descrizione_riga: 'Fornitore Alfa Srl',
      importo_dare: 0,
      importo_avere: 6197.75,
      controparte: 'Fornitore Alfa Srl',
      prima_nota: {
        id: 'pn-demo-1',
        numero_registrazione: '000001',
        data_registrazione: '2026-01-02',
        data_documento: '2026-01-02',
        numero_documento: 'FAC 25/0001',
        causale_codice: 'FF',
        causale_iva_codice: '22',
        cliente_fornitore_nome: 'Fornitore Alfa Srl',
        registro_iva_codice: '25/0001',
        protocollo_iva: '5.080,12',
        totale_dare: 6197.75,
        totale_avere: 6197.75,
      },
    },
  ]

  return demoRows.map((row, index) => buildConsultazioneRowViewModel(row, index))
}
