export const CU_CAUSALI_REDDITUALI = [
  {
    code: 'A',
    title: 'Lavoro autonomo abituale',
    officialDescription: 'Prestazioni di lavoro autonomo esercitate abitualmente.',
    category: 'lavoro autonomo',
    withholdingApplicability: 'yes',
    notes: 'Caso standard per parcelle professionali ordinarie.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: true,
    supports_inps: true,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: true,
  },
  {
    code: 'B',
    title: "Diritti d'autore e opere dell'ingegno",
    officialDescription: "Utilizzazione economica da parte dell'autore o inventore di opere dell'ingegno, brevetti e processi.",
    category: 'diritti',
    withholdingApplicability: 'yes',
    notes: 'Richiede gestione quota esclusa 21 e riduzione base imponibile per età.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: true,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'C',
    title: 'Utili da associazione in partecipazione',
    officialDescription: 'Utili spettanti ad associati in partecipazione con apporto di solo capitale o misto, ove previsti nei tracciati CU.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Da verificare in base al contratto e al regime fiscale applicabile.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'D',
    title: 'Associazione in partecipazione con apporto di lavoro',
    officialDescription: 'Utili spettanti ad associati con apporto di lavoro.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Gestione residuale, da confermare dall’operatore.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: true,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'E',
    title: 'Levata protesti',
    officialDescription: 'Compensi per levata protesti esercitata dai segretari comunali.',
    category: 'altro',
    withholdingApplicability: 'yes',
    notes: 'Caso raro.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'F',
    title: 'Indennità per cessazione rapporti di agenzia',
    officialDescription: 'Indennità e somme corrisposte alla cessazione di rapporti di agenzia e rappresentanza.',
    category: 'provvigioni',
    withholdingApplicability: 'depends',
    notes: 'Valutare il regime di tassazione separata o ordinaria.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: true,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'G',
    title: 'Indennità per cessazione lavoro autonomo',
    officialDescription: 'Indennità per la cessazione di attività sportive professionali o di rapporti simili.',
    category: 'redditi diversi',
    withholdingApplicability: 'depends',
    notes: 'Caso residuale da monitorare.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'H',
    title: 'Indennità funzioni notarili',
    officialDescription: 'Indennità per la cessazione da funzioni notarili.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Caso specialistico.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'I',
    title: 'Trasferte e rimborsi forfetari',
    officialDescription: 'Indennità di trasferta, rimborsi forfetari di spese e premi erogati a sportivi dilettanti ove ancora rilevanti nei tracciati.',
    category: 'redditi diversi',
    withholdingApplicability: 'depends',
    notes: 'Può richiedere quote non imponibili.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'L',
    title: 'Redditi da beni immobili',
    officialDescription: 'Corrispettivi o redditi derivanti da concessione in uso o sfruttamento di beni immobili.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Fuori dai casi tipici di parcella.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'M',
    title: 'Prestazioni occasionali',
    officialDescription: 'Prestazioni di lavoro autonomo non esercitate abitualmente.',
    category: 'redditi diversi',
    withholdingApplicability: 'yes',
    notes: 'Tipico per prestazioni occasionali con ritenuta.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: true,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: true,
  },
  {
    code: 'N',
    title: 'Noleggio occasionale',
    officialDescription: 'Corrispettivi da noleggio occasionale o concessione temporanea di beni mobili.',
    category: 'redditi diversi',
    withholdingApplicability: 'depends',
    notes: 'Caso residuale.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'O',
    title: 'Prestazioni non soggette a ritenuta',
    officialDescription: 'Compensi o somme erogate senza applicazione di ritenuta per specifica esclusione.',
    category: 'altro',
    withholdingApplicability: 'no',
    notes: 'Usare solo se fiscalmente coerente.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: true,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: true,
  },
  {
    code: 'O1',
    title: 'Prestazioni non soggette a ritenuta - caso specifico',
    officialDescription: 'Sottocaso di compensi non soggetti a ritenuta previsto nei tracciati CU.',
    category: 'altro',
    withholdingApplicability: 'no',
    notes: 'Da usare solo con casistica documentata.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: true,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: true,
  },
  {
    code: 'P',
    title: 'Provvigioni e mediazioni',
    officialDescription: 'Provvigioni corrisposte ad agenti, mediatori e procacciatori.',
    category: 'provvigioni',
    withholdingApplicability: 'yes',
    notes: 'Può richiedere Enasarco.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 23,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: true,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'Q',
    title: 'Caso speciale Q',
    officialDescription: 'Causale speciale CU prevista per fattispecie meno frequenti.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Alta priorità per supervisione operatore.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'R',
    title: 'Caso speciale R',
    officialDescription: 'Causale speciale CU prevista per fattispecie residuali.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Alta priorità per supervisione operatore.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'S',
    title: 'Caso speciale S',
    officialDescription: 'Causale speciale CU prevista per fattispecie residuali.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Alta priorità per supervisione operatore.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'T',
    title: 'Caso speciale T',
    officialDescription: 'Causale speciale CU prevista per fattispecie residuali.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Alta priorità per supervisione operatore.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 20,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'U',
    title: 'Utili e proventi assimilati',
    officialDescription: 'Proventi assimilati o utili residuali previsti dal tracciato CU.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Caso residuale.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'V',
    title: 'Regimi convenzionali o esenti',
    officialDescription: 'Compensi soggetti a regimi convenzionali o esenzioni specifiche.',
    category: 'altro',
    withholdingApplicability: 'no',
    notes: 'Usare con supporto documentale.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'V1',
    title: 'Regimi convenzionali o esenti - caso specifico',
    officialDescription: 'Sottocaso di regime convenzionale o esenzione previsto nei tracciati CU.',
    category: 'altro',
    withholdingApplicability: 'no',
    notes: 'Caso specialistico.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'W',
    title: 'Corrispettivi contratti di appalto',
    officialDescription: 'Corrispettivi per contratti di appalto, subappalto o prestazioni analoghe nei casi previsti.',
    category: 'provvigioni',
    withholdingApplicability: 'depends',
    notes: 'Verificare natura del rapporto.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'X',
    title: 'Canoni e corrispettivi SIAE',
    officialDescription: 'Canoni, corrispettivi o proventi SIAE e assimilati.',
    category: 'diritti',
    withholdingApplicability: 'depends',
    notes: 'Può seguire logiche simili ai diritti ma non identiche.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: true,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'Y',
    title: 'Provvigioni agenti e rappresentanti',
    officialDescription: 'Provvigioni per rapporti di agenzia, mediazione o rappresentanza.',
    category: 'provvigioni',
    withholdingApplicability: 'yes',
    notes: 'Può comportare Enasarco.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 23,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: true,
    supports_non_subject_amounts: false,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: 'Z',
    title: 'Altri titoli residuali',
    officialDescription: 'Titolo diverso dai precedenti previsto dal tracciato CU.',
    category: 'altro',
    withholdingApplicability: 'depends',
    notes: 'Da usare solo se nessuna causale specifica è applicabile.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
]

export const SOMME_NON_SOGGETTE_CODES = [
  {
    code: '21',
    title: 'Escluse da ritenuta ma rilevanti al reddito',
    officialDescription: 'Somme escluse dalla ritenuta che concorrono comunque alla formazione del reddito imponibile.',
    contributes_to_income: true,
    subject_to_withholding: false,
    notes: "Tipico per quota esclusa dei diritti d'autore.",
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: true,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: '22',
    title: 'Escluse da ritenuta e da reddito',
    officialDescription: 'Somme escluse dalla ritenuta e non concorrenti alla formazione del reddito imponibile.',
    contributes_to_income: false,
    subject_to_withholding: false,
    notes: 'Tipico per anticipazioni ex art. 15 DPR 633/72.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: true,
  },
  {
    code: '23',
    title: 'Somme escluse per specifica previsione normativa',
    officialDescription: 'Somme escluse dalla ritenuta per specifiche disposizioni normative diverse dai casi standard.',
    contributes_to_income: false,
    subject_to_withholding: false,
    notes: 'Codice residuale da usare solo con supporto normativo.',
    active: true,
    high_priority_for_automation: false,
    default_withholding_rate: 0,
    supports_cassa_previdenza: false,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: false,
    art15_logic: false,
  },
  {
    code: '24',
    title: 'Regime forfettario',
    officialDescription: 'Compensi corrisposti a soggetti in regime forfettario, esclusi da ritenuta e dai flussi CU/770 della ritenuta.',
    contributes_to_income: false,
    subject_to_withholding: false,
    notes: 'Gestione specifica forfettari; registration FF, payment PF.',
    active: true,
    high_priority_for_automation: true,
    default_withholding_rate: 0,
    supports_cassa_previdenza: true,
    supports_inps: false,
    supports_enasarco: false,
    supports_non_subject_amounts: true,
    rights_author_logic: false,
    forfettario_logic: true,
    art15_logic: false,
  },
]

export const CAUSALI_REDDITUALI_BY_CODE = Object.fromEntries(
  CU_CAUSALI_REDDITUALI.map((item) => [item.code, item])
)

export const SOMME_NON_SOGGETTE_BY_CODE = Object.fromEntries(
  SOMME_NON_SOGGETTE_CODES.map((item) => [item.code, item])
)

export const CAUSALI_REDDITUALI_OPTIONS = CU_CAUSALI_REDDITUALI
  .filter((item) => item.active)
  .map((item) => ({
    value: item.code,
    label: `${item.code} - ${item.title}`,
    description: item.officialDescription,
    meta: item,
  }))

export const SOMME_NON_SOGGETTE_OPTIONS = [
  { value: '', label: 'Nessuno', description: 'Nessun codice somme non soggette', meta: null },
  ...SOMME_NON_SOGGETTE_CODES.filter((item) => item.active).map((item) => ({
    value: item.code,
    label: `${item.code} - ${item.title}`,
    description: item.officialDescription,
    meta: item,
  })),
]

export function getCausaleReddituale(code) {
  return CAUSALI_REDDITUALI_BY_CODE[String(code || '').trim()] || null
}

export function getSommaNonSoggetta(code) {
  return SOMME_NON_SOGGETTE_BY_CODE[String(code || '').trim()] || null
}
