export const RICONCILIAZIONE_MOCK_DATA = {
  company: 'Societa Demo S.r.l.',
  bankName: 'Banca Intesa Sanpaolo S.p.A.',
  iban: 'IT60X0542811101000000123456',
  bankAccountCode: '1.01.05.001',
  statementPeriod: '12/2025',
  saldoIniziale: 24580.12,
  saldoFinaleEstratto: 31120.12,
  saldoCalcolato: 31120.12,
  saldoDifference: 0,
  kpis: [
    { label: 'Movimenti importati', value: 152, tone: 'blue', secondary: 'Estratto ultimo periodo' },
    { label: 'Da riconciliare', value: 32, tone: 'amber', secondary: 'Rimangono da verificare' },
    { label: 'Proposte forti', value: 78, tone: 'green', secondary: 'Confidence alta' },
    { label: 'Pronti', value: 24, tone: 'green', secondary: 'Conferma possibile' },
    { label: 'Bloccati', value: 6, tone: 'red', secondary: 'Correzione richiesta' },
    { label: 'Differenza saldo', value: '0,00 €', tone: 'green', secondary: 'Controllo OK' },
  ],
  summaryCards: {
    importStatus: [
      ['Banca', 'Banca Intesa Sanpaolo S.p.A.'],
      ['IBAN', 'IT60X0542811101000000123456'],
      ['Conto contabile banca', '1.01.05.001'],
      ['Periodo estratto', '01/12/2025 - 31/12/2025'],
      ['Saldo iniziale', '24.580,12 €'],
      ['Saldo finale estratto', '31.120,12 €'],
      ['Saldo calcolato', '31.120,12 €'],
      ['Differenza saldo', '0,00 €'],
    ],
    matchProps: [
      ['Abbinati', 98],
      ['Proposte forti', 78],
      ['Proposte deboli', 14],
      ['Senza match', 32],
      ['Duplicati sospetti', 6],
      ['Match con PN esistente', 41],
      ['Match con partitario', 62],
      ['Giroconti candidati', 8],
    ],
    accountingProps: [
      ['PN pronte', 24],
      ['Partite da chiudere', 56],
      ['IVA per cassa da sbloccare', 12],
      ['Ritenute da generare', 4],
      ['F24 rilevati / da dettagliare', 5],
      ['Giroconti da abbinare', 8],
      ['Movimenti sospesi', 7],
    ],
  },
  filters: {
    quick: [
      'Stato',
      'Entrate/Uscite',
      'Confidence',
      'Tipo movimento',
      'IVA per cassa',
      'Ritenute',
      'F24',
      'Giroconti',
    ],
    advanced: [
      'Data operazione da/a',
      'Data valuta da/a',
      'Importo da/a',
      'Banca/conto',
      'Causale bancaria',
      'Conto contabile proposto',
      'Partita aperta',
      'PN collegata',
      'Documento collegato',
      'decisionType',
      'cashVatImpact',
      'withholdingPaymentProposal',
    ],
  },
  movements: [
    {
      id: 'bm-001',
      status: 'Pronta',
      statusTone: 'green',
      dateOp: '21/12/2025',
      dateVal: '21/12/2025',
      description: 'Incasso cliente Rossi S.r.l.',
      counterparty: 'Rossi S.r.l.',
      entrata: 5080.12,
      uscita: 0,
      match: 'FT 255',
      confidence: 98,
      action: 'Incasso cliente',
      pn: 'Da creare',
      partitario: 'FT 255 · saldo 0,00',
      ivaCassa: 'Da sbloccare',
      withholding: 'Non applicabile',
      esito: 'OK',
      operatorConfirmed: false,
      ready: true,
      detail: {
        movement: {
          operationDate: '21/12/2025',
          valueDate: '21/12/2025',
          descriptionRaw: 'Bonifico da Rossi S.r.l. saldo FT 255',
          counterparty: 'Rossi S.r.l.',
          amount: '5.080,12 €',
          direction: 'Entrata',
          bankCausal: 'Bonifico SEPA',
          iban: 'IT29X0542811101000000123456789',
          reference: 'CRO 20251221001',
        },
        match: {
          title: 'FT 255 Rossi S.r.l.',
          confidence: '98%',
          reasons: ['Importo esatto', 'Numero fattura in descrizione', 'Controparte coerente'],
        },
        pn: {
          title: 'Incasso cliente',
          causale: 'IC - INCASSO CLIENTE',
          registrationDate: '21/12/2025',
          rows: [
            { label: 'Banca Dare', value: '5.080,12 €' },
            { label: 'Cliente Avere', value: '5.080,12 €' },
          ],
          balance: 'OK',
        },
        ledger: {
          subject: 'Rossi S.r.l.',
          document: 'FT 255',
          amountClose: '5.080,12 €',
          residualBefore: '5.080,12 €',
          residualAfter: '0,00 €',
        },
        cashVat: {
          status: 'Da sbloccare',
          document: 'FT 255',
          type: 'Incasso cliente',
          paymentAmount: '5.080,12 €',
          documentGross: '5.080,12 €',
          percentage: '100%',
          vatTotal: '916,09 €',
          vatReleased: '0,00 €',
          vatToRelease: '916,09 €',
          liquidationPeriod: '12/2025',
        },
        withholding: {
          status: 'Non applicabile',
        },
        giroconto: null,
        audit: {
          rule: 'Importo esatto + fattura in descrizione',
          confidence: '98%',
          operator: 'Non confermato',
          updatedAt: '21/12/2025 10:45',
          notes: 'Proposta forte in attesa di conferma',
        },
      },
    },
    {
      id: 'bm-002',
      status: 'Pronta',
      statusTone: 'green',
      dateOp: '22/12/2025',
      dateVal: '22/12/2025',
      description: 'Pagamento fornitore Bianchi S.n.c.',
      counterparty: 'Bianchi S.n.c.',
      entrata: 0,
      uscita: 2440.0,
      match: 'FT 789',
      confidence: 94,
      action: 'Pagamento fornitore',
      pn: 'Da creare',
      partitario: 'FT 789 · saldo 0,00',
      ivaCassa: 'No',
      withholding: 'Non applicabile',
      esito: 'OK',
      operatorConfirmed: false,
      ready: true,
      detail: {
        movement: {
          operationDate: '22/12/2025',
          valueDate: '22/12/2025',
          descriptionRaw: 'Bonifico a Bianchi S.n.c. FT 789',
          counterparty: 'Bianchi S.n.c.',
          amount: '2.440,00 €',
          direction: 'Uscita',
          bankCausal: 'Bonifico SEPA',
          iban: 'IT78X0542811101000000987654321',
          reference: 'CRO 20251222018',
        },
        match: {
          title: 'FT 789 Bianchi S.n.c.',
          confidence: '94%',
          reasons: ['Importo coerente', 'Controparte presente', 'Partita aperta trovata'],
        },
        pn: {
          title: 'Pagamento fornitore',
          causale: 'PF - PAGAMENTO FORNITORE',
          registrationDate: '22/12/2025',
          rows: [
            { label: 'Fornitore Dare', value: '2.440,00 €' },
            { label: 'Banca Avere', value: '2.440,00 €' },
          ],
          balance: 'OK',
        },
        ledger: {
          subject: 'Bianchi S.n.c.',
          document: 'FT 789',
          amountClose: '2.440,00 €',
          residualBefore: '2.440,00 €',
          residualAfter: '0,00 €',
        },
        cashVat: {
          status: 'Non applicabile',
        },
        withholding: {
          status: 'Non applicabile',
        },
        giroconto: null,
        audit: {
          rule: 'Pagamento fornitore standard',
          confidence: '94%',
          operator: 'Non confermato',
          updatedAt: '22/12/2025 15:20',
          notes: 'Chiusura partita proposta',
        },
      },
    },
    {
      id: 'bm-003',
      status: 'Pronta',
      statusTone: 'blue',
      dateOp: '22/12/2025',
      dateVal: '22/12/2025',
      description: 'Pagamento parcella Studio Verdi',
      counterparty: 'Studio Verdi',
      entrata: 0,
      uscita: 1220.0,
      match: 'Parcella 124',
      confidence: 91,
      action: 'Pagamento professionista',
      pn: 'Da creare',
      partitario: 'Parcella 124 · saldo 0,00',
      ivaCassa: 'No',
      withholding: 'Da generare',
      esito: 'OK',
      operatorConfirmed: false,
      ready: true,
      detail: {
        movement: {
          operationDate: '22/12/2025',
          valueDate: '22/12/2025',
          descriptionRaw: 'Bonifico parcella Studio Verdi - Parcella 124',
          counterparty: 'Studio Verdi',
          amount: '1.220,00 €',
          direction: 'Uscita',
          bankCausal: 'Bonifico SEPA',
          iban: 'IT12X0542811101000000567890123',
          reference: 'CRO 20251222029',
        },
        match: {
          title: 'Parcella 124 Studio Verdi',
          confidence: '91%',
          reasons: ['Numero parcella in descrizione', 'Importo coerente', 'Percipiente identificato'],
        },
        pn: {
          title: 'Pagamento professionista',
          causale: 'PP - PAGAMENTO PROFESSIONISTA',
          registrationDate: '22/12/2025',
          rows: [
            { label: 'Professionista Dare', value: '1.220,00 €' },
            { label: 'Banca Avere', value: '1.220,00 €' },
          ],
          balance: 'OK',
        },
        ledger: {
          subject: 'Studio Verdi',
          document: 'Parcella 124',
          amountClose: '1.220,00 €',
          residualBefore: '1.220,00 €',
          residualAfter: '0,00 €',
        },
        cashVat: {
          status: 'Non applicabile',
        },
        withholding: {
          status: 'Da generare',
          recipient: 'Studio Verdi',
          fiscalCode: 'VRDSTU80A01F205X',
          base: '1.000,00 €',
          rate: '20%',
          amount: '200,00 €',
          net: '1.020,00 €',
          causaleCu: 'A - Lavoro autonomo',
          tribute: '1040',
          futureDueDate: '16/01/2026',
        },
        giroconto: null,
        audit: {
          rule: 'Pagamento parcella con ritenuta da pagamento',
          confidence: '91%',
          operator: 'Non confermato',
          updatedAt: '22/12/2025 11:15',
          notes: 'Ritenuta da predisporre',
        },
      },
    },
    {
      id: 'bm-004',
      status: 'Pronta',
      statusTone: 'green',
      dateOp: '23/12/2025',
      dateVal: '23/12/2025',
      description: 'Commissioni bancarie',
      counterparty: 'Banca',
      entrata: 0,
      uscita: 12.5,
      match: 'Regola spese bancarie',
      confidence: 87,
      action: 'Spesa bancaria',
      pn: 'Da creare',
      partitario: 'Nessuna partita',
      ivaCassa: 'No',
      withholding: 'Non applicabile',
      esito: 'OK',
      operatorConfirmed: false,
      ready: true,
      detail: {
        movement: {
          operationDate: '23/12/2025',
          valueDate: '23/12/2025',
          descriptionRaw: 'Addebito commissioni bancarie',
          counterparty: 'Banca',
          amount: '12,50 €',
          direction: 'Uscita',
          bankCausal: 'Addebito spese',
          iban: 'IT60X0542811101000000123456789',
          reference: 'COMM 23122025',
        },
        match: {
          title: 'Regola spese bancarie',
          confidence: '87%',
          reasons: ['Parola chiave commissioni', 'Causale bancaria coerente'],
        },
        pn: {
          title: 'Spesa bancaria',
          causale: 'SB - SPESE BANCARIE',
          registrationDate: '23/12/2025',
          rows: [
            { label: 'Spese bancarie Dare', value: '12,50 €' },
            { label: 'Banca Avere', value: '12,50 €' },
          ],
          balance: 'OK',
        },
        ledger: {
          subject: 'Banca',
          document: 'Commissioni',
          amountClose: '12,50 €',
          residualBefore: '0,00 €',
          residualAfter: '0,00 €',
        },
        cashVat: { status: 'Non applicabile' },
        withholding: { status: 'Non applicabile' },
        giroconto: null,
        audit: { rule: 'Spesa bancaria standard', confidence: '87%', operator: 'Non confermato', updatedAt: '23/12/2025 08:40', notes: '' },
      },
    },
    {
      id: 'bm-005',
      status: 'Da dettagliare',
      statusTone: 'amber',
      dateOp: '24/12/2025',
      dateVal: '24/12/2025',
      description: 'Pagamento F24 1040',
      counterparty: 'Erario',
      entrata: 0,
      uscita: 1016.02,
      match: 'F24 rilevato',
      confidence: 72,
      action: 'Dettaglia F24',
      pn: 'Bloccata',
      partitario: 'Debito tributario',
      ivaCassa: 'No',
      withholding: 'Non applicabile',
      esito: 'Da dettagliare',
      operatorConfirmed: false,
      ready: false,
      detail: {
        movement: {
          operationDate: '24/12/2025',
          valueDate: '24/12/2025',
          descriptionRaw: 'Pagamento F24 codice tributo 1040',
          counterparty: 'Erario',
          amount: '1.016,02 €',
          direction: 'Uscita',
          bankCausal: 'F24',
          iban: '',
          reference: 'F24 1040 12/2025',
        },
        match: {
          title: 'F24 rilevato',
          confidence: '72%',
          reasons: ['Codice tributo riconosciuto', 'Importo coerente'],
        },
        pn: {
          title: 'F24 da dettagliare',
          causale: 'F24 - PAGAMENTO F24',
          registrationDate: '24/12/2025',
          rows: [
            { label: 'Debiti tributari Dare', value: '1.016,02 €' },
            { label: 'Banca Avere', value: '1.016,02 €' },
          ],
          balance: 'Bloccata',
        },
        ledger: {
          subject: 'Erario',
          document: 'F24 1040',
          amountClose: '1.016,02 €',
          residualBefore: '0,00 €',
          residualAfter: '0,00 €',
        },
        cashVat: { status: 'Non applicabile' },
        withholding: { status: 'Non applicabile' },
        giroconto: null,
        audit: { rule: 'F24 da dettagliare', confidence: '72%', operator: 'Non confermato', updatedAt: '24/12/2025 09:15', notes: 'Blocca finche manca dettaglio debito' },
      },
    },
    {
      id: 'bm-006',
      status: 'Da abbinare',
      statusTone: 'blue',
      dateOp: '24/12/2025',
      dateVal: '24/12/2025',
      description: 'Giroconto interno banca',
      counterparty: 'Banca',
      entrata: 10000.0,
      uscita: 0,
      match: 'Movimento gemello da confermare',
      confidence: 66,
      action: 'Giroconto',
      pn: 'Da creare',
      partitario: 'Movimento gemello',
      ivaCassa: 'No',
      withholding: 'Non applicabile',
      esito: 'Da abbinare',
      operatorConfirmed: false,
      ready: false,
      detail: {
        movement: {
          operationDate: '24/12/2025',
          valueDate: '24/12/2025',
          descriptionRaw: 'Giroconto interno verso conto secondario',
          counterparty: 'Banca',
          amount: '10.000,00 €',
          direction: 'Entrata',
          bankCausal: 'Giroconto',
          iban: 'IT32X0542811101000000111122223',
          reference: 'GIR 24122025',
        },
        match: {
          title: 'Movimento gemello da confermare',
          confidence: '66%',
          reasons: ['Stesso importo su conto opposto', 'Data coerente', 'Causale bancaria compatibile'],
        },
        pn: {
          title: 'Giroconto',
          causale: 'GC - GIROCONTO',
          registrationDate: '24/12/2025',
          rows: [
            { label: 'Banca destinataria Dare', value: '10.000,00 €' },
            { label: 'Banca origine Avere', value: '10.000,00 €' },
          ],
          balance: 'OK',
        },
        ledger: {
          subject: 'Banca',
          document: 'Giroconto',
          amountClose: '10.000,00 €',
          residualBefore: '0,00 €',
          residualAfter: '0,00 €',
        },
        cashVat: { status: 'Non applicabile' },
        withholding: { status: 'Non applicabile' },
        giroconto: {
          sourceBank: 'Conto principale',
          targetBank: 'Conto secondario',
          twinMovement: 'Da confermare',
          confidence: '66%',
          duplicationRisk: 'Medio',
          pnUnique: 'Proposta unica',
        },
        audit: { rule: 'Giroconto controllato', confidence: '66%', operator: 'Non confermato', updatedAt: '24/12/2025 11:25', notes: 'Serve movimento gemello' },
      },
    },
    {
      id: 'bm-007',
      status: 'Duplicata',
      statusTone: 'red',
      dateOp: '24/12/2025',
      dateVal: '24/12/2025',
      description: 'Duplicato sospetto',
      counterparty: 'N/D',
      entrata: 0,
      uscita: 500.0,
      match: 'Duplicato sospetto',
      confidence: 52,
      action: 'Segnala duplicato',
      pn: 'Bloccata',
      partitario: 'N/D',
      ivaCassa: 'No',
      withholding: 'Non applicabile',
      esito: 'Blocco',
      operatorConfirmed: false,
      ready: false,
      detail: {
        movement: {
          operationDate: '24/12/2025',
          valueDate: '24/12/2025',
          descriptionRaw: 'Movimento duplicato gia importato',
          counterparty: 'N/D',
          amount: '500,00 €',
          direction: 'Uscita',
          bankCausal: 'N/D',
          iban: '',
          reference: 'DUP-001',
        },
        match: {
          title: 'Duplicato sospetto',
          confidence: '52%',
          reasons: ['Hash duplicato', 'Stesso importo', 'Stessa data'],
        },
        pn: {
          title: 'Non committabile',
          causale: 'N/D',
          registrationDate: '24/12/2025',
          rows: [],
          balance: 'Bloccata',
        },
        ledger: {
          subject: 'N/D',
          document: 'N/D',
          amountClose: '0,00 €',
          residualBefore: '0,00 €',
          residualAfter: '0,00 €',
        },
        cashVat: { status: 'Non applicabile' },
        withholding: { status: 'Non applicabile' },
        giroconto: null,
        audit: { rule: 'Duplicato certo', confidence: '52%', operator: 'Non confermato', updatedAt: '24/12/2025 12:00', notes: 'Escludere dal commit' },
      },
    },
  ],
}
