const BANK_ACCOUNT_ID_BANCA_CORRENTE = 'bank-acc-001'
const BANK_ACCOUNT_ID_BANCA_SPESE = 'bank-acc-002'
const BANK_ACCOUNT_ID_BANCA_SECONDARIA = 'bank-acc-003'

const CONTO_BANCA_CORRENTE = {
  contoPatrimonialeId: 'conto-banca-001',
  contoPatrimonialeCodice: '1.01.01.001',
  contoPatrimonialeDescrizione: 'Banca c/c ordinario',
}

const CONTO_BANCA_SPESE = {
  contoPatrimonialeId: 'conto-banca-002',
  contoPatrimonialeCodice: '1.01.01.002',
  contoPatrimonialeDescrizione: 'Banca spese e commissioni',
}

const CONTO_CLIENTE = {
  contoPatrimonialeId: 'conto-cliente-001',
  contoPatrimonialeCodice: '1.02.02.001',
  contoPatrimonialeDescrizione: 'Crediti verso clienti',
}

const CONTO_FORNITORE = {
  contoPatrimonialeId: 'conto-fornitore-001',
  contoPatrimonialeCodice: '2.01.03.001',
  contoPatrimonialeDescrizione: 'Debiti verso fornitori',
}

const CONTO_PERCIPIENTE = {
  contoPatrimonialeId: 'conto-percipiente-001',
  contoPatrimonialeCodice: '2.02.05.001',
  contoPatrimonialeDescrizione: 'Debiti verso percipiente',
}

const CONTO_IVA_CASSA_CLIENTE = {
  contoPatrimonialeId: 'conto-cliente-iva-cassa-001',
  contoPatrimonialeCodice: '1.02.02.011',
  contoPatrimonialeDescrizione: 'Crediti verso clienti con IVA per cassa',
}

const CONTO_IVA_CASSA_FORNITORE = {
  contoPatrimonialeId: 'conto-fornitore-iva-cassa-001',
  contoPatrimonialeCodice: '2.01.03.011',
  contoPatrimonialeDescrizione: 'Debiti verso fornitori con IVA per cassa',
}

const movements = [
  // A. Incasso cliente perfetto
  {
    movementId: 'bm-001',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-02',
    valueDate: '2026-05-02',
    direction: 'in',
    amount: 1220,
    descriptionRaw: 'Bonifico da Rossi S.r.l. saldo fattura FT-2026-015',
    descriptionNormalized: 'bonifico da rossi s.r.l. saldo fattura ft 2026 015',
    counterpartyName: 'Rossi S.r.l.',
    counterpartyIban: 'IT29X0542811101000000123456789',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.98,
    status: 'imported',
  },
  // B. Pagamento fornitore perfetto
  {
    movementId: 'bm-002',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-03',
    valueDate: '2026-05-03',
    direction: 'out',
    amount: 2440,
    descriptionRaw: 'Bonifico a Bianchi S.n.c. saldo fattura FB-551',
    descriptionNormalized: 'bonifico a bianchi s.n.c. saldo fattura fb 551',
    counterpartyName: 'Bianchi S.n.c.',
    counterpartyIban: 'IT78X0542811101000000987654321',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.97,
    status: 'imported',
  },
  // C. Pagamento parziale fornitore
  {
    movementId: 'bm-003',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-04',
    valueDate: '2026-05-04',
    direction: 'out',
    amount: 800,
    descriptionRaw: 'Acconto fornitore Bianchi S.n.c. fattura FB-552',
    descriptionNormalized: 'acconto fornitore bianchi s.n.c. fattura fb 552',
    counterpartyName: 'Bianchi S.n.c.',
    counterpartyIban: 'IT78X0542811101000000987654321',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.93,
    status: 'imported',
  },
  // D. Incasso parziale cliente
  {
    movementId: 'bm-004',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-05',
    valueDate: '2026-05-05',
    direction: 'in',
    amount: 500,
    descriptionRaw: 'Incasso parziale cliente Verdi S.r.l. fattura VC-44',
    descriptionNormalized: 'incasso parziale cliente verdi s.r.l. fattura vc 44',
    counterpartyName: 'Verdi S.r.l.',
    counterpartyIban: 'IT44X0542811101000000129999999',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.92,
    status: 'needs_review',
  },
  // E. Pagamento cumulativo fornitori
  {
    movementId: 'bm-005',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-06',
    valueDate: '2026-05-06',
    direction: 'out',
    amount: 1800,
    descriptionRaw: 'Bonifico cumulativo a Bianchi S.n.c. partite FB-553 FB-554 FB-555',
    descriptionNormalized: 'bonifico cumulativo a bianchi s.n.c. partite fb 553 fb 554 fb 555',
    counterpartyName: 'Bianchi S.n.c.',
    counterpartyIban: 'IT78X0542811101000000987654321',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.89,
    status: 'needs_review',
  },
  // F. Incasso cliente ambiguo
  {
    movementId: 'bm-006',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-07',
    valueDate: '2026-05-07',
    direction: 'in',
    amount: 1000,
    descriptionRaw: 'Bonifico cliente Neri S.r.l. saldo fattura 1000',
    descriptionNormalized: 'bonifico cliente neri s.r.l. saldo fattura 1000',
    counterpartyName: 'Neri S.r.l.',
    counterpartyIban: 'IT61X0542811101000000111111111',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.71,
    status: 'needs_review',
  },
  // G. Spesa bancaria
  {
    movementId: 'bm-007',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_SPESE,
    bankAccountCode: CONTO_BANCA_SPESE.contoPatrimonialeCodice,
    operationDate: '2026-05-08',
    valueDate: '2026-05-08',
    direction: 'out',
    amount: 12,
    descriptionRaw: 'Addebito spese bancarie e commissioni mensili',
    descriptionNormalized: 'addebito spese bancarie e commissioni mensili',
    counterpartyName: 'Banca',
    counterpartyIban: null,
    bankCausal: 'SPESE E COMMISSIONI',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.96,
    status: 'imported',
  },
  // H. F24
  {
    movementId: 'bm-008',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-09',
    valueDate: '2026-05-09',
    direction: 'out',
    amount: 1840,
    descriptionRaw: 'F24 Agenzia Entrate delega 1840 tributi vari',
    descriptionNormalized: 'f24 agenzia entrate delega 1840 tributi vari',
    counterpartyName: 'Agenzia Entrate',
    counterpartyIban: null,
    bankCausal: 'F24',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.95,
    status: 'blocked',
  },
  // I. Giroconto
  {
    movementId: 'bm-009',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-10',
    valueDate: '2026-05-10',
    direction: 'out',
    amount: 5000,
    descriptionRaw: 'Giroconto verso banca secondaria per riallineamento liquidita',
    descriptionNormalized: 'giroconto verso banca secondaria per riallineamento liquidita',
    counterpartyName: 'Banca secondaria',
    counterpartyIban: 'IT39X0101503200000070745491',
    bankCausal: 'GIROCONTO',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.91,
    status: 'needs_review',
  },
  // J. Parcella professionista con ritenuta
  {
    movementId: 'bm-010',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-11',
    valueDate: '2026-05-11',
    direction: 'out',
    amount: 1000,
    descriptionRaw: 'Bonifico Studio Rossi parcella 124 netto pagamento',
    descriptionNormalized: 'bonifico studio rossi parcella 124 netto pagamento',
    counterpartyName: 'Studio Rossi',
    counterpartyIban: 'IT12X0542811101000000567890123',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.94,
    status: 'needs_review',
  },
  // K. IVA per cassa su incasso cliente
  {
    movementId: 'bm-011',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-12',
    valueDate: '2026-05-12',
    direction: 'in',
    amount: 2440,
    descriptionRaw: 'Incasso cliente Delta S.r.l. fattura IVAC-01 IVA per cassa',
    descriptionNormalized: 'incasso cliente delta s.r.l. fattura ivac 01 iva per cassa',
    counterpartyName: 'Delta S.r.l.',
    counterpartyIban: 'IT23X0542811101000000222222222',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.95,
    status: 'imported',
  },
  // L. IVA per cassa su pagamento fornitore
  {
    movementId: 'bm-012',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-13',
    valueDate: '2026-05-13',
    direction: 'out',
    amount: 1220,
    descriptionRaw: 'Pagamento fornitore Gamma S.r.l. fattura IVAC-02 IVA per cassa',
    descriptionNormalized: 'pagamento fornitore gamma s.r.l. fattura ivac 02 iva per cassa',
    counterpartyName: 'Gamma S.r.l.',
    counterpartyIban: 'IT31X0542811101000000333333333',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.95,
    status: 'imported',
  },
  // M. Movimento senza match
  {
    movementId: 'bm-013',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-14',
    valueDate: '2026-05-14',
    direction: 'out',
    amount: 73.45,
    descriptionRaw: 'Addebito generico vario',
    descriptionNormalized: 'addebito generico vario',
    counterpartyName: 'Da identificare',
    counterpartyIban: null,
    bankCausal: 'ADDEBITO',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.42,
    status: 'needs_review',
  },
  // N. Movimento duplicato potenziale
  {
    movementId: 'bm-014',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-15',
    valueDate: '2026-05-15',
    direction: 'in',
    amount: 1220,
    descriptionRaw: 'Bonifico da Rossi S.r.l. saldo fattura FT-2026-015 duplicato',
    descriptionNormalized: 'bonifico da rossi s.r.l. saldo fattura ft 2026 015 duplicato',
    counterpartyName: 'Rossi S.r.l.',
    counterpartyIban: 'IT29X0542811101000000123456789',
    bankCausal: 'BONIFICO SEPA',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.96,
    status: 'blocked',
  },
  // O. Movimento da ignorare
  {
    movementId: 'bm-015',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_CORRENTE,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-16',
    valueDate: '2026-05-16',
    direction: 'out',
    amount: 0,
    descriptionRaw: 'Saldo iniziale contabile non movimentato',
    descriptionNormalized: 'saldo iniziale contabile non movimentato',
    counterpartyName: null,
    counterpartyIban: null,
    bankCausal: 'SALDO INIZIALE',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 1,
    status: 'ignored',
  },
  // Ulteriore caso di movimento senza match con testo generico e importo non riconciliabile
  {
    movementId: 'bm-016',
    bankAccountId: BANK_ACCOUNT_ID_BANCA_SECONDARIA,
    bankAccountCode: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    operationDate: '2026-05-17',
    valueDate: '2026-05-17',
    direction: 'in',
    amount: 31.2,
    descriptionRaw: 'Versamento generico non classificabile',
    descriptionNormalized: 'versamento generico non classificabile',
    counterpartyName: 'Da identificare',
    counterpartyIban: null,
    bankCausal: 'VERSAMENTO',
    sourceStatementId: 'stmt-banco-2026-05',
    confidence: 0.35,
    status: 'needs_review',
  },
]

const partiteAperte = [
  // Cliente Rossi: caso perfetto e caso IVA per cassa
  {
    partitaId: 'part-001',
    soggettoId: 'sogg-cl-001',
    soggettoTipo: 'cliente',
    soggettoNome: 'Rossi S.r.l.',
    documentoId: 'doc-cl-001',
    documentoTipo: 'fattura_cliente',
    numeroDocumento: 'FT-2026-015',
    dataDocumento: '2026-04-12',
    dataScadenza: '2026-05-12',
    importoOriginario: 1220,
    importoAperto: 1220,
    contoPatrimonialeId: CONTO_CLIENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_CLIENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_CLIENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura cliente',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-002',
    soggettoId: 'sogg-cl-002',
    soggettoTipo: 'cliente',
    soggettoNome: 'Verdi S.r.l.',
    documentoId: 'doc-cl-002',
    documentoTipo: 'fattura_cliente',
    numeroDocumento: 'VC-44',
    dataDocumento: '2026-04-20',
    dataScadenza: '2026-05-20',
    importoOriginario: 1000,
    importoAperto: 1000,
    contoPatrimonialeId: CONTO_CLIENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_CLIENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_CLIENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura cliente',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-003',
    soggettoId: 'sogg-cl-003',
    soggettoTipo: 'cliente',
    soggettoNome: 'Delta S.r.l.',
    documentoId: 'doc-cl-003',
    documentoTipo: 'fattura_cliente',
    numeroDocumento: 'IVAC-01',
    dataDocumento: '2026-04-01',
    dataScadenza: '2026-06-01',
    importoOriginario: 2440,
    importoAperto: 2440,
    contoPatrimonialeId: CONTO_IVA_CASSA_CLIENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_IVA_CASSA_CLIENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_IVA_CASSA_CLIENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura cliente',
    ivaPerCassa: true,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  // Fornitore Bianchi: pagamento perfetto e pagamento parziale
  {
    partitaId: 'part-004',
    soggettoId: 'sogg-for-001',
    soggettoTipo: 'fornitore',
    soggettoNome: 'Bianchi S.n.c.',
    documentoId: 'doc-for-001',
    documentoTipo: 'fattura_fornitore',
    numeroDocumento: 'FB-551',
    dataDocumento: '2026-04-10',
    dataScadenza: '2026-05-10',
    importoOriginario: 2440,
    importoAperto: 2440,
    contoPatrimonialeId: CONTO_FORNITORE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_FORNITORE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_FORNITORE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura fornitore',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-005',
    soggettoId: 'sogg-for-001',
    soggettoTipo: 'fornitore',
    soggettoNome: 'Bianchi S.n.c.',
    documentoId: 'doc-for-002',
    documentoTipo: 'fattura_fornitore',
    numeroDocumento: 'FB-552',
    dataDocumento: '2026-04-15',
    dataScadenza: '2026-05-15',
    importoOriginario: 1600,
    importoAperto: 1600,
    contoPatrimonialeId: CONTO_FORNITORE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_FORNITORE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_FORNITORE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura fornitore',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-006',
    soggettoId: 'sogg-for-001',
    soggettoTipo: 'fornitore',
    soggettoNome: 'Bianchi S.n.c.',
    documentoId: 'doc-for-003',
    documentoTipo: 'fattura_fornitore',
    numeroDocumento: 'FB-553',
    dataDocumento: '2026-04-18',
    dataScadenza: '2026-05-18',
    importoOriginario: 700,
    importoAperto: 700,
    contoPatrimonialeId: CONTO_FORNITORE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_FORNITORE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_FORNITORE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura fornitore',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  // Incassi/pagamenti generici e casi ambigui
  {
    partitaId: 'part-007',
    soggettoId: 'sogg-cl-004',
    soggettoTipo: 'cliente',
    soggettoNome: 'Neri S.r.l.',
    documentoId: 'doc-cl-004',
    documentoTipo: 'fattura_cliente',
    numeroDocumento: 'NR-100',
    dataDocumento: '2026-04-22',
    dataScadenza: '2026-05-22',
    importoOriginario: 1000,
    importoAperto: 1000,
    contoPatrimonialeId: CONTO_CLIENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_CLIENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_CLIENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura cliente',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-008',
    soggettoId: 'sogg-cl-004',
    soggettoTipo: 'cliente',
    soggettoNome: 'Neri S.r.l.',
    documentoId: 'doc-cl-005',
    documentoTipo: 'fattura_cliente',
    numeroDocumento: 'NR-101',
    dataDocumento: '2026-04-23',
    dataScadenza: '2026-05-23',
    importoOriginario: 1000,
    importoAperto: 1000,
    contoPatrimonialeId: CONTO_CLIENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_CLIENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_CLIENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura cliente',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  // Professionista con ritenuta
  {
    partitaId: 'part-009',
    soggettoId: 'sogg-per-001',
    soggettoTipo: 'percipiente',
    soggettoNome: 'Studio Rossi',
    documentoId: 'doc-per-001',
    documentoTipo: 'parcella_professionista',
    numeroDocumento: 'PAR-124',
    dataDocumento: '2026-04-28',
    dataScadenza: '2026-05-28',
    importoOriginario: 1220,
    importoAperto: 1220,
    contoPatrimonialeId: CONTO_PERCIPIENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_PERCIPIENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_PERCIPIENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'parcella professionista',
    ivaPerCassa: false,
    ritenuta: true,
    statoPartita: 'aperta',
  },
  // Partite per caso cumulativo
  {
    partitaId: 'part-010',
    soggettoId: 'sogg-for-002',
    soggettoTipo: 'fornitore',
    soggettoNome: 'Bianchi S.n.c.',
    documentoId: 'doc-for-004',
    documentoTipo: 'fattura_fornitore',
    numeroDocumento: 'FB-554',
    dataDocumento: '2026-04-19',
    dataScadenza: '2026-05-19',
    importoOriginario: 500,
    importoAperto: 500,
    contoPatrimonialeId: CONTO_FORNITORE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_FORNITORE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_FORNITORE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura fornitore',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-011',
    soggettoId: 'sogg-for-002',
    soggettoTipo: 'fornitore',
    soggettoNome: 'Bianchi S.n.c.',
    documentoId: 'doc-for-005',
    documentoTipo: 'fattura_fornitore',
    numeroDocumento: 'FB-555',
    dataDocumento: '2026-04-21',
    dataScadenza: '2026-05-21',
    importoOriginario: 600,
    importoAperto: 600,
    contoPatrimonialeId: CONTO_FORNITORE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_FORNITORE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_FORNITORE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura fornitore',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  {
    partitaId: 'part-012',
    soggettoId: 'sogg-for-002',
    soggettoTipo: 'fornitore',
    soggettoNome: 'Bianchi S.n.c.',
    documentoId: 'doc-for-006',
    documentoTipo: 'fattura_fornitore',
    numeroDocumento: 'FB-556',
    dataDocumento: '2026-04-25',
    dataScadenza: '2026-05-25',
    importoOriginario: 700,
    importoAperto: 700,
    contoPatrimonialeId: CONTO_FORNITORE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_FORNITORE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_FORNITORE.contoPatrimonialeDescrizione,
    causaleOrigine: 'fattura fornitore',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'aperta',
  },
  // Movimento da ignorare / saldi tecnici
  {
    partitaId: 'part-013',
    soggettoId: 'sogg-sys-001',
    soggettoTipo: 'cliente',
    soggettoNome: 'Saldo iniziale tecnico',
    documentoId: 'doc-sys-001',
    documentoTipo: 'altro',
    numeroDocumento: 'INIT-2026',
    dataDocumento: '2026-01-01',
    dataScadenza: '2026-01-01',
    importoOriginario: 0,
    importoAperto: 0,
    contoPatrimonialeId: CONTO_BANCA_CORRENTE.contoPatrimonialeId,
    contoPatrimonialeCodice: CONTO_BANCA_CORRENTE.contoPatrimonialeCodice,
    contoPatrimonialeDescrizione: CONTO_BANCA_CORRENTE.contoPatrimonialeDescrizione,
    causaleOrigine: 'saldo iniziale',
    ivaPerCassa: false,
    ritenuta: false,
    statoPartita: 'contestata',
  },
]

const expectedCases = [
  {
    caseId: 'A',
    movementId: 'bm-001',
    expectedDecisionType: 'match_partita',
    expectedMovementType: 'incasso_cliente',
    expectedMatchType: 'exact_amount',
    expectedPartitaId: 'part-001',
    expectedConfidence: 'high',
    expectedWarnings: [],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'INCASSO_CLIENTE',
      descrizione: 'Incasso cliente Rossi S.r.l. FT-2026-015',
      righe: [
        { sezione: 'Dare', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 1220 },
        { sezione: 'Avere', conto: 'Crediti verso clienti', tipoConto: 'conto_patrimoniale_cliente', importo: 1220 },
      ],
      partitarioImpact: { action: 'chiusura_partita', partitaId: 'part-001', importoChiusura: 1220 },
    },
  },
  {
    caseId: 'B',
    movementId: 'bm-002',
    expectedDecisionType: 'match_partita',
    expectedMovementType: 'pagamento_fornitore',
    expectedMatchType: 'exact_amount',
    expectedPartitaId: 'part-004',
    expectedConfidence: 'high',
    expectedWarnings: [],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'PAGAMENTO_FORNITORE',
      descrizione: 'Pagamento fornitore Bianchi S.n.c. FB-551',
      righe: [
        { sezione: 'Dare', conto: 'Debiti verso fornitori', tipoConto: 'conto_patrimoniale_fornitore', importo: 2440 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 2440 },
      ],
      partitarioImpact: { action: 'chiusura_partita', partitaId: 'part-004', importoChiusura: 2440 },
    },
  },
  {
    caseId: 'C',
    movementId: 'bm-003',
    expectedDecisionType: 'match_parziale',
    expectedMovementType: 'pagamento_fornitore',
    expectedMatchType: 'partial_amount',
    expectedPartitaId: 'part-005',
    expectedConfidence: 'medium',
    expectedWarnings: ['residuo_partita_da_mantenere'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'PAGAMENTO_FORNITORE',
      descrizione: 'Acconto fornitore Bianchi S.n.c. FB-552',
      righe: [
        { sezione: 'Dare', conto: 'Debiti verso fornitori', tipoConto: 'conto_patrimoniale_fornitore', importo: 800 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 800 },
      ],
      partitarioImpact: { action: 'chiusura_parziale', partitaId: 'part-005', importoChiusura: 800, residuoAtteso: 800 },
    },
  },
  {
    caseId: 'D',
    movementId: 'bm-004',
    expectedDecisionType: 'match_parziale',
    expectedMovementType: 'incasso_cliente',
    expectedMatchType: 'partial_amount',
    expectedPartitaId: 'part-002',
    expectedConfidence: 'medium',
    expectedWarnings: ['residuo_partita_da_mantenere'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'INCASSO_CLIENTE',
      descrizione: 'Incasso parziale cliente Verdi S.r.l. VC-44',
      righe: [
        { sezione: 'Dare', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 500 },
        { sezione: 'Avere', conto: 'Crediti verso clienti', tipoConto: 'conto_patrimoniale_cliente', importo: 500 },
      ],
      partitarioImpact: { action: 'chiusura_parziale', partitaId: 'part-002', importoChiusura: 500, residuoAtteso: 500 },
    },
  },
  {
    caseId: 'E',
    movementId: 'bm-005',
    expectedDecisionType: 'match_parziale',
    expectedMovementType: 'pagamento_fornitore',
    expectedMatchType: 'cumulative_candidate',
    expectedPartitaId: null,
    expectedConfidence: 'medium',
    expectedWarnings: ['richiesta_conferma_operatore', 'candidato_cumulativo'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'PAGAMENTO_FORNITORE_MULTIPLO',
      descrizione: 'Pagamento cumulativo a Bianchi S.n.c. per FB-553 FB-554 FB-555',
      righe: [
        { sezione: 'Dare', conto: 'Debiti verso fornitori', tipoConto: 'conto_patrimoniale_fornitore', importo: 1800 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 1800 },
      ],
      partitarioImpact: {
        action: 'chiusura_multipla',
        partitaIds: ['part-006', 'part-010', 'part-011', 'part-012'],
        importoChiusura: 1800,
        requireOperatorConfirmation: true,
      },
    },
  },
  {
    caseId: 'F',
    movementId: 'bm-006',
    expectedDecisionType: 'match_partita',
    expectedMovementType: 'incasso_cliente',
    expectedMatchType: 'ambiguous',
    expectedPartitaId: null,
    expectedConfidence: 'low',
    expectedWarnings: ['piu_partite_stesso_importo', 'scelta_operatore_richiesta'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'INCASSO_CLIENTE',
      descrizione: 'Incasso cliente Neri S.r.l. importo ambiguo',
      righe: [
        { sezione: 'Dare', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 1000 },
        { sezione: 'Avere', conto: 'Crediti verso clienti', tipoConto: 'conto_patrimoniale_cliente', importo: 1000 },
      ],
      partitarioImpact: { action: 'richiedi_scelta_operatore', candidatePartitaIds: ['part-007', 'part-008'] },
    },
  },
  {
    caseId: 'G',
    movementId: 'bm-007',
    expectedDecisionType: 'classificazione_diretta',
    expectedMovementType: 'spesa_bancaria',
    expectedMatchType: 'not_required',
    expectedPartitaId: null,
    expectedConfidence: 'high',
    expectedWarnings: [],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'SPESE_BANCARIE',
      descrizione: 'Spese bancarie e commissioni mensili',
      righe: [
        { sezione: 'Dare', conto: 'Spese bancarie', tipoConto: 'conto_costo', importo: 12 },
        { sezione: 'Avere', conto: 'Banca spese e commissioni', tipoConto: 'conto_banca', importo: 12 },
      ],
      partitarioImpact: { action: 'nessuna' },
    },
  },
  {
    caseId: 'H',
    movementId: 'bm-008',
    expectedDecisionType: 'f24',
    expectedMovementType: 'f24',
    expectedMatchType: 'not_required',
    expectedPartitaId: null,
    expectedConfidence: 'high',
    expectedWarnings: ['richiedere_dettaglio_tributi'],
    expectedBlockers: ['tributi_mancanti'],
    expectedAccountingProposal: {
      causaleBancaria: 'F24',
      descrizione: 'Pagamento F24 Agenzia Entrate',
      righe: [
        { sezione: 'Dare', conto: 'Debiti tributari', tipoConto: 'conto_passivo', importo: 1840 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 1840 },
      ],
      partitarioImpact: { action: 'nessuna' },
    },
  },
  {
    caseId: 'I',
    movementId: 'bm-009',
    expectedDecisionType: 'giroconto',
    expectedMovementType: 'giroconto',
    expectedMatchType: 'not_required',
    expectedPartitaId: null,
    expectedConfidence: 'high',
    expectedWarnings: ['controparte_banca_da_selezionare'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'GIROCONTO',
      descrizione: 'Giroconto verso banca secondaria',
      righe: [
        { sezione: 'Dare', conto: 'Banca secondaria', tipoConto: 'conto_banca', importo: 5000 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 5000 },
      ],
      partitarioImpact: { action: 'nessuna' },
    },
  },
  {
    caseId: 'J',
    movementId: 'bm-010',
    expectedDecisionType: 'match_partita',
    expectedMovementType: 'pagamento_parcella',
    expectedMatchType: 'exact_amount',
    expectedPartitaId: 'part-009',
    expectedConfidence: 'high',
    expectedWarnings: ['ritenuta_collegata_da_verificare'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'PAGAMENTO_PARCELLA',
      descrizione: 'Pagamento parcella Studio Rossi PAR-124',
      righe: [
        { sezione: 'Dare', conto: 'Debiti verso percipiente', tipoConto: 'conto_patrimoniale_percipiente', importo: 1000 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 1000 },
      ],
      partitarioImpact: { action: 'chiusura_partita', partitaId: 'part-009', importoChiusura: 1000 },
    },
    withholdingPaymentProposal: {
      applies: true,
      percipienteId: 'sogg-per-001',
      ritenutaId: 'rit-124',
      amount: 200,
      warning: 'La ritenuta resta da collegare al flusso fiscale futuro; il pagamento chiude il netto.',
    },
  },
  {
    caseId: 'K',
    movementId: 'bm-011',
    expectedDecisionType: 'match_partita',
    expectedMovementType: 'incasso_cliente',
    expectedMatchType: 'exact_amount',
    expectedPartitaId: 'part-003',
    expectedConfidence: 'high',
    expectedWarnings: ['iva_per_cassa_da_sbloccare_proporzionalmente'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'INCASSO_CLIENTE',
      descrizione: 'Incasso cliente Delta S.r.l. IVAC-01',
      righe: [
        { sezione: 'Dare', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 2440 },
        { sezione: 'Avere', conto: 'Crediti verso clienti con IVA per cassa', tipoConto: 'conto_patrimoniale_cliente', importo: 2440 },
      ],
      partitarioImpact: { action: 'chiusura_partita', partitaId: 'part-003', importoChiusura: 2440 },
    },
    cashVatImpact: {
      applies: true,
      direction: 'incasso_cliente',
      documentId: 'doc-cl-003',
      taxableAmountReleased: 2000,
      vatAmountReleased: 440,
      proportion: 1,
      warning: 'LIVA per cassa si rende esigibile in base allincasso registrato.',
    },
  },
  {
    caseId: 'L',
    movementId: 'bm-012',
    expectedDecisionType: 'match_partita',
    expectedMovementType: 'pagamento_fornitore',
    expectedMatchType: 'exact_amount',
    expectedPartitaId: null,
    expectedConfidence: 'high',
    expectedWarnings: ['iva_per_cassa_da_sbloccare_proporzionalmente'],
    expectedBlockers: [],
    expectedAccountingProposal: {
      causaleBancaria: 'PAGAMENTO_FORNITORE',
      descrizione: 'Pagamento fornitore Gamma S.r.l. IVAC-02',
      righe: [
        { sezione: 'Dare', conto: 'Debiti verso fornitori con IVA per cassa', tipoConto: 'conto_patrimoniale_fornitore', importo: 1220 },
        { sezione: 'Avere', conto: 'Banca c/c ordinario', tipoConto: 'conto_banca', importo: 1220 },
      ],
      partitarioImpact: { action: 'chiusura_partita', partitaId: null, importoChiusura: 1220 },
    },
    cashVatImpact: {
      applies: true,
      direction: 'pagamento_fornitore',
      documentId: 'doc-for-iva-cassa-001',
      taxableAmountReleased: 1000,
      vatAmountReleased: 220,
      proportion: 1,
      warning: 'LIVA per cassa diventa detraibile con il pagamento.',
    },
  },
  {
    caseId: 'M',
    movementId: 'bm-013',
    expectedDecisionType: 'nessun_match',
    expectedMovementType: 'movimento_da_classificare',
    expectedMatchType: 'no_match',
    expectedPartitaId: null,
    expectedConfidence: 'low',
    expectedWarnings: ['movimento_non_riconciliabile'],
    expectedBlockers: [],
    expectedAccountingProposal: null,
  },
  {
    caseId: 'N',
    movementId: 'bm-014',
    expectedDecisionType: 'blocked',
    expectedMovementType: 'incasso_cliente',
    expectedMatchType: 'ambiguous',
    expectedPartitaId: 'part-001',
    expectedConfidence: 'low',
    expectedWarnings: ['potenziale_duplicato', 'movimento_gia_riconciliato_o_presente'],
    expectedBlockers: ['duplicato_potenziale'],
    expectedAccountingProposal: null,
  },
  {
    caseId: 'O',
    movementId: 'bm-015',
    expectedDecisionType: 'ignora_movimento',
    expectedMovementType: 'movimento_da_classificare',
    expectedMatchType: 'not_required',
    expectedPartitaId: null,
    expectedConfidence: 'high',
    expectedWarnings: ['saldo_iniziale_non_riconciliabile'],
    expectedBlockers: [],
    expectedAccountingProposal: null,
  },
  {
    caseId: 'O2',
    movementId: 'bm-016',
    expectedDecisionType: 'nessun_match',
    expectedMovementType: 'movimento_da_classificare',
    expectedMatchType: 'no_match',
    expectedPartitaId: null,
    expectedConfidence: 'low',
    expectedWarnings: ['descrizione_generica', 'no_match'],
    expectedBlockers: [],
    expectedAccountingProposal: null,
  },
]

export const RICONCILIAZIONE_MATCHING_FIXTURES = {
  metadata: {
    version: 'r7a-1',
    domainLanguage: 'canonico_fiscosim',
    note: 'Dataset mock per riconciliazione bancaria. Non contiene logica di matching.',
  },
  movements,
  partiteAperte,
  expectedCases,
}

export function getRiconciliazioneMatchingFixtures() {
  return RICONCILIAZIONE_MATCHING_FIXTURES
}

export function getExpectedDecisionForMovement(movementId) {
  return RICONCILIAZIONE_MATCHING_FIXTURES.expectedCases.find((item) => item.movementId === movementId) || null
}

export function getMovementFixtureById(movementId) {
  return RICONCILIAZIONE_MATCHING_FIXTURES.movements.find((item) => item.movementId === movementId) || null
}

export function getPartitaFixtureById(partitaId) {
  return RICONCILIAZIONE_MATCHING_FIXTURES.partiteAperte.find((item) => item.partitaId === partitaId) || null
}