alter table if exists public.causali_contabili
  add column if not exists descrizione_tabulati text,
  add column if not exists tipo_causale text,
  add column if not exists operazione_partite text,
  add column if not exists tipo_pagamento text,
  add column if not exists codice_registro_iva text,
  add column if not exists protocollo_numerazione integer default 0,
  add column if not exists segno_registro_iva text,
  add column if not exists codice_aliquota_iva text,
  add column if not exists op_ritenute text,
  add column if not exists tipo_documento text,
  add column if not exists data_documento text,
  add column if not exists numero_documento text,
  add column if not exists tipo_doc_comunicaz_ft text,
  add column if not exists tipo_doc_ft_elettroniche text,
  add column if not exists conto_iva_esig_differita text,
  add column if not exists registro_iva_differita text,
  add column if not exists registro_iva_cee text,
  add column if not exists protocollo_iva_cee integer default 0,
  add column if not exists segno_iva_registro_cee text,
  add column if not exists trascina_descrizione boolean default true,
  add column if not exists trascina_sbilancio boolean default false,
  add column if not exists data_competenza boolean default false,
  add column if not exists rateo_risconti boolean default false,
  add column if not exists disattivato boolean default false,
  add column if not exists integrazione_documento boolean default false,
  add column if not exists causale_giro_iva_cassa boolean default false,
  add column if not exists competenza_iva_anno_prec boolean default false,
  add column if not exists causale_standard_efat boolean default false,
  add column if not exists ventilazione_corrispettivi boolean default false,
  add column if not exists esclusa_integrazioni boolean default false,
  add column if not exists note text;
